// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpG-Hb1JvUoA3llU8Zw1dFD-jBE8aK1Y',
    appId: '1:373847001764:web:fe4a04fe82fdffe57ef431',
    messagingSenderId: '373847001764',
    projectId: 'openheart-68bd1',
    authDomain: 'openheart-68bd1.firebaseapp.com',
    storageBucket: 'openheart-68bd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD42iKIyhsGeTDPW2YeLSmryT4Exdgi9A4',
    appId: '1:373847001764:android:a8a96d1a18b9aab07ef431',
    messagingSenderId: '373847001764',
    projectId: 'openheart-68bd1',
    storageBucket: 'openheart-68bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxZ98w4lKmTJJCsZbzH1uqP6b8ebDwL8',
    appId: '1:373847001764:ios:5c1df34be6a1540a7ef431',
    messagingSenderId: '373847001764',
    projectId: 'openheart-68bd1',
    storageBucket: 'openheart-68bd1.firebasestorage.app',
    iosBundleId: 'com.example.openheart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxZ98w4lKmTJJCsZbzH1uqP6b8ebDwL8',
    appId: '1:373847001764:ios:5c1df34be6a1540a7ef431',
    messagingSenderId: '373847001764',
    projectId: 'openheart-68bd1',
    storageBucket: 'openheart-68bd1.firebasestorage.app',
    iosBundleId: 'com.example.openheart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpG-Hb1JvUoA3llU8Zw1dFD-jBE8aK1Y',
    appId: '1:373847001764:web:fe4a04fe82fdffe57ef431',
    messagingSenderId: '373847001764',
    projectId: 'openheart-68bd1',
    authDomain: 'openheart-68bd1.firebaseapp.com',
    storageBucket: 'openheart-68bd1.firebasestorage.app',
  );
}
